<template>
  <div v-if="state" class="loading">
    <div class="loadingio-spinner-bean-eater-5wfj31gfo6x">
      <div class="ldio-1p3kvhj8q2a">
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
      <!-- <div>加载中</div> -->
    </div>
  </div>
</template>

<script lang="ts">
import { ref, defineComponent } from 'vue'
export default defineComponent({
  setup() {
    const state = ref(false)
    const hide = () => {
      state.value = false
    }
    const show = () => {
      state.value = true
    }
    return {
      state,
      hide,
      show
    }
  }
})
</script>
<style lang="less" scoped>
// .loading {
//   position: fixed;
//   left: 0;
//   top: 0;
//   right: 0;
//   bottom: 0;
//   background: rgba(0, 0, 0, 0.5);
//   z-index: 999999;
// }

@keyframes ldio-1p3kvhj8q2a-1 {
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(-45deg);
  }
  100% {
    transform: rotate(0deg);
  }
}
@keyframes ldio-1p3kvhj8q2a-2 {
  0% {
    transform: rotate(180deg);
  }
  50% {
    transform: rotate(225deg);
  }
  100% {
    transform: rotate(180deg);
  }
}
.ldio-1p3kvhj8q2a > div:nth-child(2) {
  transform: translate(-15px, 0);
}
.ldio-1p3kvhj8q2a > div:nth-child(2) div {
  position: absolute;
  top: 25.4px;
  left: 25.4px;
  width: 76.2px;
  height: 38.1px;
  border-radius: 76.2px 76.2px 0 0;
  background: #ff3b3b;
  animation: ldio-1p3kvhj8q2a-1 1s linear infinite;
  transform-origin: 38.1px 38.1px;
}
.ldio-1p3kvhj8q2a > div:nth-child(2) div:nth-child(2) {
  animation: ldio-1p3kvhj8q2a-2 1s linear infinite;
}
.ldio-1p3kvhj8q2a > div:nth-child(2) div:nth-child(3) {
  transform: rotate(-90deg);
  animation: none;
}
@keyframes ldio-1p3kvhj8q2a-3 {
  0% {
    transform: translate(120.65px, 0);
    opacity: 0;
  }
  20% {
    opacity: 1;
  }
  100% {
    transform: translate(44.45px, 0);
    opacity: 1;
  }
}
.ldio-1p3kvhj8q2a > div:nth-child(1) {
  display: block;
}
.ldio-1p3kvhj8q2a > div:nth-child(1) div {
  position: absolute;
  top: 58.42px;
  left: -5.08px;
  width: 10.16px;
  height: 10.16px;
  border-radius: 50%;
  background: #ff3b3b;
  animation: ldio-1p3kvhj8q2a-3 1s linear infinite;
}
.ldio-1p3kvhj8q2a > div:nth-child(1) div:nth-child(1) {
  animation-delay: -0.67s;
}
.ldio-1p3kvhj8q2a > div:nth-child(1) div:nth-child(2) {
  animation-delay: -0.33s;
}
.ldio-1p3kvhj8q2a > div:nth-child(1) div:nth-child(3) {
  animation-delay: 0s;
}
.loadingio-spinner-bean-eater-5wfj31gfo6x {
  width: 127px;
  height: 127px;
  display: inline-block;
  overflow: hidden;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  // background: #f1f2f3;
}
.ldio-1p3kvhj8q2a {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-1p3kvhj8q2a div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
